#!/bin/bash
# setup script
set -e

# dotfiles
git clone https://github.com/zedchance/dotfiles.git /dotfiles

# oh-my-zsh
sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# vim config / plugins
mkdir -p /root/.vim/colors
curl -fLo /root/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
ln -s /dotfiles/.vimrc /root/
ln -s /dotfiles/akintoij.vim /root/.vim/colors/

